# Spring Boot application name
spring.application.name=file-upload-service

spring.config.import=optional:aws-parameterstore:/config/file-upload-service/
aws.s3-bucket=aws/s3-bucket
aws.region=aws/region
aws.profile=file-upload-dev

# Server port
server.port=8080

#aws.paramstore.access-key=/file-storage-service/aws/access-key
#aws.paramstore.secret-key=/file-storage-service/aws/secret-key
#aws.paramstore.bucketName=/file-storage-service/aws/s3-bucket
#spring.cloud.aws.region.static=ap-south-1

