spring.application.name=file-storage-service
spring.config.import=optional:aws-parameterstore:/file-storage-service/aws

cloud.aws.region.static=ap-south-1

# Aliases for Parameter Store paths
access.key=${access-key}
secret.key=${secret-key}
bucket.name=${s3-bucket}


# Parameter Store names (use SecureString for the values)
# aws.ssm.access-key-param=/file-storage-service/aws/access-key
# aws.ssm.secret-key-param=/file-storage-service/aws/secret-key
# aws.ssm.bucket-param=/file-storage-service/aws/s3-bucket
# aws.s3.region=ap-south-1

